### PR TITLE
More conspicuous download button

### LINKED ISSUE #1040: Make download button at library.kiwix.org more conspicuous
We've received repeat comments from users that they at first can't figure out where the download function is. The download button as it stands could be a bit more conspicuous, including an actual download icon. 

The file size that is also included in the download text could be moved somewhere else on the card so as to make space for the download icon.

### LINKED ISSUE #1130: On the nojs library page the download button click area is misleading
In no-JS mode (`/nojs`) download buttons on the book tiles slightly misbehave. The button invites clicking it anywhere in the button area (since it becomes darker and the mouse cursor changes when hovering over any region of the button rect) however the clicks only work on the text of the button. There is no such issue in JSful mode.

### PR DESCRIPTION
**Pull request by kelson42**
Fixes #1040
Fixes #1130

### CODE REVIEW

**Comment by veloman-yunkan** [comment]
@kelson42 Who is going to review this PR? I wanted to add *you* as a reviewer, but GitHub won't let me do it.

**Comment by kelson42** [comment]
@veloman-yunkan Please review and fix. The code is from @juuz0. I think the proposal of improvement is OK. I have only one small concern: the grey borders around the new blue button even if perfectly there, look inexistant which - at least to me - give the impression that the button is smaller than the box (1px left and 1px right). Do you have also this feeling?

**Comment by veloman-yunkan** [comment]
> Please review and fix. The code is from @juuz0.

I know. I already modified @juuz0's changes, pushed the branch and was going to create a PR when GitHub told me that there is already a PR (this one) associated with that branch. It would be strange if I review my own PR. 

> I think the proposal of improvement is OK.

Which proposal of improvement do you mean?
 
> I have only one small concern: the grey borders around the new blue button even if perfectly there, look inexistant which - at least to me - give the impression that the button is smaller than the box (1px left and 1px right). Do you have also this feeling?

It didn't catch my attention but after looking closely - yes, it looks like that.

**Comment by veloman-yunkan** [comment]
> > I have only one small concern: the grey borders around the new blue button even if perfectly there, look inexistant which - at least to me - give the impression that the button is smaller than the box (1px left and 1px right). Do you have also this feeling?
> 
> It didn't catch my attention but after looking closely - yes, it looks like that.

Fixed by changing the border color to that of the button itself.

**Comment by kelson42** [comment]
> > > I have only one small concern: the grey borders around the new blue button even if perfectly there, look inexistant which - at least to me - give the impression that the button is smaller than the box (1px left and 1px right). Do you have also this feeling?
> > 
> > 
> > It didn't catch my attention but after looking closely - yes, it looks like that.
> 
> Fixed by changing the border color to that of the button itself.

Great, but now we have some kind of white framing appearing if highlighed.
image

**Comment by veloman-yunkan** [comment]
> > > > I have only one small concern: the grey borders around the new blue button even if perfectly there, look inexistant which - at least to me - give the impression that the button is smaller than the box (1px left and 1px right). Do you have also this feeling?
> > > 
> > > 
> > > It didn't catch my attention but after looking closely - yes, it looks like that.
> > 
> > 
> > Fixed by changing the border color to that of the button itself.
> 
> Great, but now we have some kind of white framing appearing if highlighed. image

There is no such effect under Firefox, but I confirm that I could observe it under Chromium.

**Comment by veloman-yunkan** [comment]
> > > > > I have only one small concern: the grey borders around the new blue button even if perfectly there, look inexistant which - at least to me - give the impression that the button is smaller than the box (1px left and 1px right). Do you have also this feeling?
> > > > 
> > > > 
> > > > It didn't catch my attention but after looking closely - yes, it looks like that.
> > > 
> > > 
> > > Fixed by changing the border color to that of the button itself.
> > 
> > 
> > Great, but now we have some kind of white framing appearing if highlighed. image
> 
> There is no such effect under Firefox, but I confirm that I could observe it under Chromium.

Fixed in a different way. @kelson42 Please test again.

**Comment by veloman-yunkan** [comment]
@kelson42 Note that I didn't update the cacheid's. I will update them (and make the CI pass) while squashing the fixup commits once we are done with the visual appearance issues.

**Comment by kelson42** [comment]
@veloman-yunkan Thx! Good to merge then when commits are reorganised!

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan Thx! Good to merge then when commits are reorganised!

Done

**Comment by veloman-yunkan** [comment]
I discovered two bugs (#1129 and #1130). The latter one is actually introduced by this PR, so maybe I better fix it before this PR is merged.

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]
No-JS page contains a usability bug (#1130).

**Review by veloman-yunkan — APPROVED** [review]

**Pull request merged**
