### PR TITLE
Ungarbled binary resources

### LINKED ISSUE #1129: Binary resources in libkiwix have been broken by dos2unix conversion
The last commit of #1113 (https://github.com/kiwix/libkiwix/pull/1113/commits/4812fb18f6374eaafb98fca9bae075987c8ab436) has broken the binary resources of libkiwix.

This shows up as PNG icons failing to display in the frontend:

image

### PR DESCRIPTION
**Pull request by veloman-yunkan**
Fixes #1129

### CODE REVIEW

**Comment by veloman-yunkan** [comment]
This PR fixes the bug introduced by #1113. More importantly it provides protection (in the form of a unit test) against similar future problems.

There are a few things that I don't like about this PR:

- It works by invoking an external command (a small python script) to perform a HTTP request and compute the hash of the response. I chose that approach in order to avoid having to introduce a dependency on a library providing support for SHA1 computation.
- The list of static resources checked by the new test (as well a few old ones) is hardcoded and must be manually updated when new resources are added.
- The list of file extensions considered to be binary (and thus to be excluded from dos2unix conversion) is hardcoded and must be updated when new types of binary resources are introduced.

**Comment by veloman-yunkan** [comment]
@kelson42 How shall we proceed with this PR without @mgautierfr? I am most interested in feedback on the proposed method of protection against bugs similar to the one being fixed.

**Comment by kelson42** [comment]
@veloman-yunkan We have to deal without his feedback. But I have two remarks:
* I'm concerned by the growing difficulty of updating these static files
* This needs at least an update IMHO of https://github.com/kiwix/libkiwix/blob/main/README.md#static-files-compilation

**Comment by veloman-yunkan** [comment]
> * The list of file extensions considered to be binary (and thus to be excluded from dos2unix conversion) is hardcoded and must be updated when new types of binary resources are introduced.

Now when new types of resources are added that won't go unnoticed - the build will fail unless the list of known extensions is updated.

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan We have to deal without his feedback. But I have two remarks:
> 
>   * I'm concerned by the growing difficulty of updating these static files

With the newly committed change no extra difficulty regarding maintenance of static resource files is being introduced  (as long as we are concerned only with things that have to be memorized). The second point in [my earlier comment](https://github.com/kiwix/libkiwix/pull/1131#issuecomment-2343809865) is just a reiteration of a (slight) problem that existed before this PR. There is a way to add a test that would mostly eliminate that issue but IMHO we shouldn't spend any effort on it until it proves to be a real rather than a hypothetical problem. 

>   * This needs at least an update IMHO of https://github.com/kiwix/libkiwix/blob/main/README.md#static-files-compilation

I reread the README but don't think that it needs to be updated. If the pressure to do so mounts, we better enhance our test suite as mentioned in the previous paragraph.

>   * I wonder if tackling [We need to test frontend js code. #815](https://github.com/kiwix/libkiwix/issues/815) would not be a better approach

That may solve some of the addressed concerns (though at the cost of a significantly larger effort) but should not be considered as a substitute for what can be checked on the unit-test level.

>   * What about [Rethink how we integrate resources in binaries. #31](https://github.com/kiwix/libkiwix/issues/31) ?

Our mechanism for embedding resources has been significantly enhanced since when the original issue was filed. That on the one hand makes that ticket more justified since the system has become more complex and perhaps can be optimized. On the other hand the task has become more difficult too and maybe we shouldn't touch what works reasonably well until we notice that we have to spend excessive hours on solving issues rooted in the current implementation of how we deal with static resources.

**Pull request merged**
