### PR TITLE
Small kiwix-serve welcome page CSS fix

### LINKED ISSUE #812: Small glitch in kiwix-serve welcome page tile title
With current kiwix-hotspot `3.3.0-1`:
image

With `dev` version:
image

The margin right after the icon is far too short.

### PR DESCRIPTION
**Pull request by kelson42**
Fixes #812

### CODE REVIEW

**Comment by kelson42** [comment]
@juuz0 @veloman-yunkan How to recompile the resources? It seems to be documented nowhere!

**Comment by veloman-yunkan** [comment]
> @juuz0 @veloman-yunkan How to recompile the resources? It seems to be documented nowhere!

@kelson42 Just modify the resource and build - the resource should be recompiled automatically.

**Comment by kelson42** [comment]
@veloman-yunkan I will check again then. Thx.

**Comment by kelson42** [comment]
@veloman-yunkan I have run `rm -rf ./build/ && meson . build && ninja -C build && sudo ninja -C build install` but then I only get:
```bash
$ git status
On branch small-css-fix
Your branch is up to date with 'origin/small-css-fix'.
```

So something seems wrong somewhere, right?

**Comment by veloman-yunkan** [comment]
@kelson42 What exactly is wrong? If you expected `git status` to show the `build` subdirectory in the list of untracked files, note that it is `.gitignore`d.

**Review by juuz0 — APPROVED** [review]
LGTM, fixed the value in test/server.cpp

**Comment by kelson42** [comment]
> @kelson42 What exactly is wrong? If you expected `git status` to show the `build` subdirectory in the list of untracked files, note that it is `.gitignore`d.

This exactly what is misleading and should be at least documented.

**Comment by veloman-yunkan** [comment]
> > @kelson42 What exactly is wrong? If you expected `git status` to show the `build` subdirectory in the list of untracked files, note that it is `.gitignore`d.
> 
> This exactly what is misleading and should be at least documented.

@kelson42 Any more or less experienced user of git shouldn't be confused by this. I don't think that we have to document the widely used features of our development tools.

**Pull request merged**
