### PR TITLE
JNI search  methods for android

### PR DESCRIPTION
**Pull request by gouri-panda**
Created all search methods that we need for searching in `kiwix-android`
libkiwix already has filters and class that we want to search e.g [Book](https://github.com/kiwix/libkiwix/blob/master/src/wrapper/java/org/kiwix/kiwixlib/Book.java) and [Filter](https://github.com/kiwix/libkiwix/blob/master/src/wrapper/java/org/kiwix/kiwixlib/Filter.java) that we will reuse in android to filter all sort of things.
After this process will be in android
1. libkiwix will build the URL 
2. client shares the OPDS feed with libkiwix which parse it and in returns gives the list of books as an object

### CODE REVIEW

**Comment by gouri-panda** [comment]
@kelson42 @mhutti1 @abdulwd I think that's what we need to replace to search the OPDS URL call and retrieve the OPDS feed.

**Comment by kelson42** [comment]
@gouri-panda thx, but why this pr is here and not in repo openzim/java-libzim?

**Comment by gouri-panda** [comment]
@kelson42 `openzim/java-libzim` isn't functional yet. When that will happen I will remove this work to that repo. Is it ok with you?

**Comment by kelson42** [comment]
It isn't functional here neither because we can not publish to bintray anymore. What is the plan to fix that problem?

**Comment by gouri-panda** [comment]
@kelson42 I am planning to build locally to work in android for a short amount of time.If it is possible I'll try to create a PR by the end of today.

**Comment by kelson42** [comment]
Ok, but none of this will pass the CI, because it is not in bintray/maeven... so it won't be really mergeable.

**Comment by gouri-panda** [comment]
>but none of this will pass the CI, because it is not in bintray/maeven.

@kelson42 I'm sorry, but what isn't in bintrary/maevn?

**Comment by mgautierfr** [comment]
We should move to java-libkiwix the sooner possible. Having two repository in parallel will complicate a lot the process (if we merge this PR here, we will have to backport the change in java-libkiwix, with all the complexity of the a conflicting merge between two different repository)

**Pull request closed without merging**
