### PR TITLE
added nofilter attribute and iframe conditions

### LINKED ISSUE #585: kiwix-serve (ZIM?) should propose widgets
_From @kelson42 on June 19, 2016 15:28_

People using kiwix-serve within integrated solution like Rachel, XSCE, Ideascube use it with other content coming from other sources. They need at some point to add a menu entry to point to that content. It might be interesting for kiwix-serve to propose an easy to integrate widget to make their life easier. This widget beside describing the content would for example provide a searchbox which in one click would allow to find a content.

_Copied from original issue: kiwix/kiwix-xulrunner#245_

### PR DESCRIPTION
**Pull request by MananJethwani**
this resolves #585

### CODE REVIEW

**Comment by MananJethwani** [comment]
To include a widget on the MediaWiki server we will require https://www.mediawiki.org/wiki/Extension:Iframe, and to make it a bit responsive we need to use `width:100%` for some reason vh and vw don't work for the MediaWiki based servers.

**Comment by mgautierfr** [comment]
@MananJethwani Is this PR a draft or ready to be reviewed ?

**Comment by MananJethwani** [comment]
@mgautierfr it's still a draft, @kelson42 asked me too test it on a wiki but for some reason I am not able to use widget extension for mediawiki as of now....will have a look in some time after solving some other tickets.

**Comment by kelson42** [comment]
@juuz0 Please consider this PR. We will have to decide if hidding completly the top searchbar should be done like this via a parameter, or this can be done easily, just by customising the CSS of iframe HTML (to me sounds preferable).

**Pull request closed without merging**
