### PR TITLE
Optimized kiwix-serve welcome page

### PR DESCRIPTION
**Pull request by ankur12-1610**
Fixes: [kiwix-tools/#538](https://github.com/kiwix/kiwix-tools/issues/538)

Before: 
153743002-48e1f36a-d9a6-43a6-83f6-93532dab6150

After:
kiwix-media

### CODE REVIEW

**Comment by ankur12-1610** [comment]
@kelson42 can you please review?

**Review by kelson42 — CHANGES_REQUESTED** [review]
@ankur12-1610 Thank you for your PR. It indeed works better now, but I'm not really happy with the solution because there is still an asymetry between the left and the right. The tiles should maximize the space usage and be distributed in the middle horizontaly. So the whole block of the book list should be centered horizontally.

**Comment by ankur12-1610** [comment]
> @ankur12-1610 Thank you for your PR. It indeed works better now, but I'm not really happy with the solution because there is still an asymetry between the left and the right. The tiles should maximize the space usage and be distributed in the middle horizontaly. So the whole block of the book list should be centered horizontally.

@kelson42 got it. So the current padding is `20px 5vw 20px 10vw`, the soultion whould be that I change it to `20px 5vw 20px 5vw` right?

**Comment by ankur12-1610** [comment]
@kelson42 I've made the required changes kindly review :)

**Comment by kelson42** [comment]
@ankur12-1610 This is getting better, but it seems not propoer for all screens. See here, it is not centered properly
image

**Comment by kelson42** [comment]
@ankur12-1610 Any news on this PR?

**Comment by ankur12-1610** [comment]
Hey @kelson42 sorry for the late reply

I'm working on it and will update the PR bt a day or two :')

**Comment by kelson42** [comment]
@ankur12-1610 thx!

**Comment by ankur12-1610** [comment]
@kelson42 I did the changes, although in a little unorthodox way :sweat_smile:, by testing every float value :)

**Comment by kelson42** [comment]
Superseeded by #786

**Pull request closed without merging**
