### PR TITLE
Minor UI language selection improvements

### LINKED ISSUE #900: Add a "pointer" cursor and tool-tip on UI language selector.
Small suggestion (from @juuz0)
Maybe the UI language selector icon could have cursor as "pointer" & a tool-tip to tell what it does

_Originally posted by @juuz0 in https://github.com/kiwix/libkiwix/issues/846#issuecomment-1438697702_

### PR DESCRIPTION
**Pull request by veloman-yunkan**
Fixes #900

Added cursor type and hints to the UI language selection button. The hints are always in English since seeing a hint in an unfamiliar language doesn't help and English is the current lingua franca.

### CODE REVIEW

**Review by juuz0 — COMMENTED** [review]
LGTM.

Little observation, though unrelated to this issue but since its about minor improvements, we could fix it here:

In welcome page, font shows correctly
image

But it doesn't while browsing a book
image

**Comment by veloman-yunkan** [comment]
> In welcome page, font shows correctly 
> But it doesn't while browsing a book

This is a manifestation of a more general discrepancy in the look-and-feel of the welcome page and the viewer page. I think we better address it separately.

**Comment by kelson42** [comment]
> > In welcome page, font shows correctly 
> > But it doesn't while browsing a book
> 
> This is a manifestation of a more general discrepancy in the look-and-feel of the welcome page and the viewer page. I think we better address it separately.

Please don't forget to create the ticket then.

**Comment by veloman-yunkan** [comment]
> > > In welcome page, font shows correctly
> > > But it doesn't while browsing a book
> > 
> > 
> > This is a manifestation of a more general discrepancy in the look-and-feel of the welcome page and the viewer page. I think we better address it separately.
> 
> Please don't forget to create the ticket then.

Done (#917)

**Comment by juuz0** [comment]
needs a rebase!

**Comment by kelson42** [comment]
Everybody seems to agree, I will merge.

**Review by kelson42 — APPROVED** [review]
LGTM

**Review by kelson42 — CHANGES_REQUESTED** [review]
@veloman-yunkan Actually I don't think this is ready to merge because this hints/attributes for impaired users are not translated... and they should like the others (se for example viewer topbar).

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan Actually I don't think this is ready to merge because this hints/attributes for impaired users are not translated... and they should like the others (se for example viewer topbar).

@kelson42 That was done on purpose and is stated in the PR description. If the current UI is in the wrong language and you want to change the language, then being presented with a hint in a language you don't understand doesn't help. That's why I chose to not translate the text of these special hints.

**Pull request merged**
