### PR TITLE
Localisation updates from https://translatewiki.net.

### PR DESCRIPTION
**Pull request by translatewiki**
Translation updates

### CODE REVIEW

**Comment by kelson42** [comment]
@veloman-yunkan OK to merge?

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan OK to merge?

Yes, but the translations for new languages must be registered (by running the `static/generate_i18n_resources_list.py` script) so that they actually become available in libkiwix.

**Comment by kelson42** [comment]
@veloman-yunkan You can not run the script and update PR?

**Review by veloman-yunkan — APPROVED** [review]

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan You can not run the script and update PR?

@kelson42 Done

**Pull request merged**
