### PR TITLE
Less confusing 404 errors from /random, /meta and /suggest endpoints

### PR DESCRIPTION
**Pull request by veloman-yunkan**
Related to kiwix/kiwix-tools#506 (but not sure if it can be considered a fix)

### CODE REVIEW

**Comment by kelson42** [comment]
@veloman It's nice to have a dedicated message now, but 2 buttons of 3 are still away!
image

I probably don't understand everything but the approach of `Response::build_404` seems correct ot if:
* We have a proper message (you made one)
* The mainpage/random buttons are still there is the bookname is valid.

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan It's nice to have a dedicated message now, but 2 buttons of 3 are still away!

@kelson42 Fixed that too

**Review by kelson42 — APPROVED** [review]
@veloman-yunkan Thank for the last fix From the user perspective it works like expected and to my opinion it fixes the issue. Do you haad something else in mind?

Regarding `/meta` and `/suggest` end-points I don't have tested anything because I don't know what problem is fixed and how.

@mgautierfr Please have a look to the code

**Review by mgautierfr — APPROVED** [review]
I approve.

I am bit disturbed by making the "term" optional. But it is not so important. The search for a empty term will return something anyway and the API is used "internally".

**Pull request merged**
