### PR TITLE
Support for multiple illustrations in OPDS entry

### LINKED ISSUE #533: OPDS Icon is limited
At the moment, most ZIM only include a `Favicon` metadata that is 48px squared due to the requirement in the spec and the fact that kiwix-serve has only ever displayed it.

Some ZIM don't respect it and include different resolution/form-factor.

With the ability to now use higher definition illustrations via the `Illustration` metadata, it's important those are used when available and pertinent. I suppose kiwix-serve might use it for its homepage redesign.

With the global switch to OPDS in readers, it's important that those higher definition images are available through OPDS, to accomodate the platform/reader needs. On a high DPI (retina) display, the 48px is blurry unless scaled down to 24px which is **very small**.

I have no suggestion on how that should be done. The current node reads as:

```xml
<icon>/meta?name=favicon&amp;content=gutenberg_sv_all_2021-05</icon>
```

### PR DESCRIPTION
**Pull request by veloman-yunkan**
Fixes #533

Things to note:

- the output is modified in both old and new (v2) OPDS API
- the code is not tested on a ZIM file with multiple illustrations for the lack of such a ZIM file

### CODE REVIEW

**Review by mgautierfr — CHANGES_REQUESTED** [review]
We also have to update the handle_meta method to handle the `illustration_<with>x<height>` name. (https://github.com/kiwix/libkiwix/blob/master/src/server/internalServer.cpp#L348-L368)

(This probably should have been done in PR adapting libkiwix to new api in libzim but I forget about it)

**Comment by kelson42** [comment]
@veloman-yunkan Can you please rebase on master? Is this PR again ready to review (then please request a new review)?

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan Can you please rebase on master? Is this PR again ready to review (then please request a new review)?

Done without adding a test case utilizing a ZIM archive with multiple illustrations (because of no easy way of creating such a ZIM archive using existing tools, and the complexities of the procedure of modifying test ZIM data).

**Comment by kelson42** [comment]
@veloman-yunkan I'm worried about your last comment. Having a proper test set of ZIM and libkiwix properly tested with the most common scenarios is important. What is exactly unclear, after @rgaudin feedback to your last question at https://github.com/kiwix/libkiwix/issues/533#issuecomment-875900305, I thought this is OK now... but it seems this is not. We should get that sorted out. If this is a not a detail which stops you, please open a ticket so we can resolve the problem.

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan I'm worried about your last comment. Having a proper test set of ZIM and libkiwix properly tested with the most common scenarios is important. What is exactly unclear, after @rgaudin feedback to your last question at [#533 (comment)](https://github.com/kiwix/libkiwix/issues/533#issuecomment-875900305), I thought this is OK now... but it seems this is not. We should get that sorted out. If this is a not a detail which stops you, please open a ticket so we can resolve the problem.

@kelson42 

@rgaudin's suggestion requires a custom build of `zimwriterfs` (using modified source code). I could figure out such a "solution" myself and it is not what I was looking for. I think that the test data must be created in a reproducible way, using official versions of publicly available tools. Regarding the complexity of test data management, note that libkiwix doesn't yet rely on `zim-testing-suite` and so far hasn't respected the requirement of keeping old test data and continuing to use it for backward compatibility testing.

**Comment by mgautierfr** [comment]
I agree with this PR. (Code and comment)

- This is pretty difficult to test this (to have test data).
- This code is pretty easy to change if there is a problem and is not really part of the API.

I think we can merge like this and add correct tests later when we will attack the zim testing suite problem.

@veloman-yunkan please rebase-fixup on master.

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan please rebase-fixup on master.

Done

**Comment by kelson42** [comment]
I'm not understanding the arguments to not test this. I would like to have a talk with @mgautierfr about this ticket before merging this.

**Comment by veloman-yunkan** [comment]
Rebased again (had to resolve a conflict with #576)

**Comment by kelson42** [comment]
I understand that this PR can not easily be tested properly (at least) because of:
* https://github.com/kiwix/libkiwix/issues/601
* https://github.com/openzim/zim-testing-suite/issues/3
* https://github.com/openzim/zim-testing-suite/issues/4

I have there open the tickets above to help in the future and will merge this PR now.

**Pull request merged**
