### PR TITLE
Changed word "language" to "category" in README.mdS

### PR DESCRIPTION
**Pull request by Bigguysahaj**

### CODE REVIEW

**Comment by Bigguysahaj** [comment]
Hey,
Can anyone please explain to me or refer me to some reading material on why this happened.
I'm new to open source and didn't really set up linux environment before this (I didn't think you needed it to update documentation).

A response would be greatly appreciated.

**Comment by veloman-yunkan** [comment]
@Bigguysahaj Don't worry. Your change has nothing to do with the CI failure.

**Comment by Bigguysahaj** [comment]
Was it because I didn't create an issue or a well-written description regarding the problem.

If that's the case, I will make sure for next time.

**Comment by veloman-yunkan** [comment]
@Bigguysahaj No, it is just a glitch in our CI.

**Comment by kelson42** [comment]
@Bigguysahaj please remove your last commit, not merge in a feature branch.

**Comment by Bigguysahaj** [comment]
> @Bigguysahaj please remove your last commit, not merge in a feature branch.

The one that shows accepted? or the original one.
Sorry for the trouble.

**Comment by kelson42** [comment]
If you can not remove the merge, please squash everything in one commit.

**Comment by Bigguysahaj** [comment]
@kelson42 I reverted my latest commit.

**Comment by kelson42** [comment]
@Bigguysahaj Please squash everything in one commit.

**Comment by Bigguysahaj** [comment]
I'm sorry @kelson42 , I am not able to squash everything in one commit.
I tried updating and rebasing and all it did was create another commit. Can you just hint me on what I'm doing wrong.

**Comment by kelson42** [comment]
here a doc https://www.git-tower.com/learn/git/faq/git-squash. If you don't know this is your duty to search and find documentation how to do it.

**Comment by Bigguysahaj** [comment]
> If you don't know this is your duty to search and find documentation how to do it

Okay yes, I will try that

**Comment by Bigguysahaj** [comment]
I finally did learn how to git squash through interactive rebasing and I still think something is wrong, the number of commits is increasing as opposed to being squashed in one (which is what I expected would happen). Is it wrong?

**Comment by Bigguysahaj** [comment]
@kelson42 I think I did it, please check. It was an unexpected struggle but I did learn git well in the process.
Also during the process, I also pulled some of the recently updated files by other contributors, and hence my request shows 10 files. Should I try getting rid of them or the version control might handle it?

**Review by kelson42 — APPROVED** [review]

**Pull request merged**
